# Example Web Server Configuration (.conf)
# Ref: https://nginx.org/en/docs/beginners_guide.html

server {
    listen 8090;
    server_name localhost blog.com www.blog.com example.com;
    client_max_body_size 5000;

    error_page 404 /errors/404_custom.html;
    error_page 500 /errors/500_custom.html;

    location / {
        root /var/www/;
        index index.html;
        allow_methods GET POST;
    }

    # Specific upload location
    location /uploads {
        root /var/www/uploads;
        allow_methods POST DELETE;
    }


    # Location for static images with directory listing enabled
    # location /images/ {
    #     root /var/www/example.com/assets;
    #     autoindex on; # Enable directory listing if index file not found
    #     allow_methods GET POST;
    # }

    location /cgi-bin/ {
       cgi on; # Enable CGI processing
       root /var/www/cgi-bin;
       allow_methods GET POST; # Allow GET and POST for scripts
    }

    # Location demonstrating a permanent redirect
    # location /old-page.html {
    #     root /var/www/blablabla.com;
    #     redirect 301 http://example.com/new-page.html;
    # }

    #1
    # location /api/ {
    #     root /var/www/bin;
    #     allow_methods GET; 
    # }

    #2
    # location /api {
    #     root /var/www/bin;
    #     allow_methods GET; 
    # }

    #3
    # location /api/users {
    #     root /var/www/bin;
    #     allow_methods GET; 
    # }

    #4
    # location /api/users/ {
    #     root /var/www/bin;
    #     allow_methods GET; 
    # }

    #5
    location /blogs {
        root /var/www/bin;
        allow_methods GET; 
    }
    
}

# Server 2: Handles requests for api.example.com 
server {
    listen 8080;
    server_name api.example.com www.api.example.com localhost;

    # API endpoint using Python CGI
    location / {
        root /var/www/api;
        allow_methods GET POST;
        # cgi ; 
    }
}

# # Server 3: Listens on a different port (8080) for internal services
# server {
#     listen 127.0.0.1:8080; # Listen only on localhost, port 8080
#     # No server_name, acts as default for 127.0.0.1:8080

#     location /status {
#         root /var/www/status_app;
#         index status.html;