# Example Web Server Configuration (.conf)
# Ref: https://nginx.org/en/docs/beginners_guide.html

server {
    listen 8090;
    server_name localhost blog.com www.blog.com example.com;
    client_max_body_size 50M;

    error_page 404 /var/www/errors/404_custom.html;
    error_page 500 /var/www/errors/500_custom.html;

    location / {
        root /var/www/example.com;
        index index.html;
        allow_methods GET POST;
    }

    location /uploads {
        root /var/www/uploads;
        allow_methods POST DELETE;
    }

    location /autoindex {
        root /var/www/files;
        autoindex on;
        allow_methods GET POST;
    }

    location /cgi-bin/ {
       cgi on;
       root /var/www/cgi-bin;
       allow_methods GET POST;
    }

    location /redirect/ {
        root /var/www/empty;
        redirect 301 /files/cat-css/cat.html;
    }

    location /forbidden {
        root /var/www/empty;
        allow_methods POST;
    }

    #1
    # location /api/ {
    #     root /var/www/bin;
    #     allow_methods GET; 
    # }

    #2
    # location /api {
    #     root /var/www/bin;
    #     allow_methods GET; 
    # }    
}

# Server 2: Handles requests for api.example.com 
#server {
#    listen 8080;
#    server_name api.example.com www.api.example.com localhost;

#    # API endpoint using Python CGI
#    location / {
#        root /var/www/api;
#        allow_methods GET POST;
#        # cgi ; 
#    }
#}

# # Server 3: Listens on a different port (8080) for internal services
# server {
#     listen 127.0.0.1:8080; # Listen only on localhost, port 8080
#     # No server_name, acts as default for 127.0.0.1:8080

#     location /status {
#         root /var/www/status_app;
#         index status.html;