server {
    listen 8000;
    server_name example.com localhost;

    # API endpoint using Python CGI
    location / {
        root /var/www/YoupiBanane;
        allow_methods GET;
		index index.html;
    }

	location /put_test/ {
		root /var/www/YoupiBanane;
		allow_methods POST;
		index index.html;
	}

	location /post_body {
		root /var/www/YoupiBanane;
		allow_methods POST;
		index index.html;
		client_max_body_size 100;
	}

	location /directory {
		root /var/www/YoupiBanane;
		allow_methods GET; 
		index youpi.bad_extension;
	}

	location .bla {
		root /var/www/YoupiBanane;
		allow_methods GET POST;
		index cgi_tester;
		cgi on;
	}
}
